directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false

detectors:
  NilCheck:
    enabled: false
  "db/migrate":
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
    TooManyStatements:
      enabled: false
    DuplicateMethodCall:
      enabled: false
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    TooManyInstanceVariables:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  "app/models/concerns":
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
    TooManyInstanceVariables:
      enabled: false
  "spec/mailers/previews":
    UtilityFunction:
      enabled: false
  TooManyStatements:
    max_statements: 15
  NestedIterators:
    max_allowed_nesting: 3
  LongParameterList:
    max_params: 4
  TooManyMethods:
    max_methods: 20
  "app/validators":
      FeatureEnvy:
        enabled: false
      ControlParameter:
        enabled: false
      UtilityFunction:
        enabled: false

exclude_paths:
  - test/channels/application_cable
